name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: b64
      with: 
        filePath: ./index.js
    -  run: |
        if [ ${{steps.b64.outputs.base64}} == $(cat ./index.js | base64) ]; then
          exit
        else
          exit 1
        fi