name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm i
    - uses: ./
      with: 
        filePath: ./index.js
      id: b64
      run: ${{steps.b64.outputs.base64}} == $(cat ./index.js | base64)